/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const ToggleAll = (props) => {
    return <input
        className="toggle-all"
        type="checkbox"
        onChange={props.onChange}
        checked={props.checked}
    />

}


/******* S.D.G. *******/



