/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {toggleAll} from "../../../../gen/todo/ActionFunctions";

export const ToggleAll = (props) => {
    return 						<input
        className="toggle-all"
        type="checkbox"
        onChange={toggleAll}
        checked={props.checked}
    />

}


/******* S.D.G. *******/



