/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import React from "react";

export function uiElement(attributes) {
	if (attributes.errorMessage) {
		return <pre className="error">{attributes.errorMessage}</pre>
	}
	return null;
}



/******* S.D.G. *******/



