/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import React from "react";
import {clearDone} from "../../../gen/todo/ActionFunctions";

export function uiElement(attributes) {
	const itemsString = attributes.itemCount === 1 ? 'item' : 'items';
	return <footer className="footer">
		<span className="todo-count">
			{`${attributes.itemCount} ${itemsString} left`}
		</span>
		<ul className="filters">
			<li>
				<a href={`#/${attributes.categoryId}`} className={attributes.filter === 'all' ? 'selected' : ''}>All</a>
			</li>
			<li>
				<a href={`#/${attributes.categoryId}/open`} className={attributes.filter === 'open' ? 'selected' : ''}>Active</a>
			</li>
			<li>
				<a href={`#/${attributes.categoryId}/done`} className={attributes.filter === 'done' ? 'selected' : ''}>Completed</a>
			</li>
		</ul>
		<button className="clear-completed" onClick={clearDone}>Clear completed</button>
	</footer>
}



/******* S.D.G. *******/



