/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const Footer = (props) => {
	const itemsString = props.itemCount === 1 ? 'item' : 'items';
	return <footer className="footer">
		<span className="todo-count">
			{`${props.itemCount} ${itemsString} left`}
		</span>
		{props.children}
	</footer>
}



/******* S.D.G. *******/



