/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";
import {clearDone} from "../../../gen/todo/ActionFunctions";


export const Footer = (props) => {
	const itemsString = props.itemCount === 1 ? 'item' : 'items';
	return <footer className="footer">
		<span className="todo-count">
			{`${props.itemCount} ${itemsString} left`}
		</span>
		<ul className="filters">
			<li>
				<a href={`#/${props.categoryId}`} className={props.filter === 'all' ? 'selected' : ''}>All</a>
			</li>
			<li>
				<a href={`#/${props.categoryId}/open`} className={props.filter === 'open' ? 'selected' : ''}>Active</a>
			</li>
			<li>
				<a href={`#/${props.categoryId}/done`} className={props.filter === 'done' ? 'selected' : ''}>Completed</a>
			</li>
		</ul>
		<button className="clear-completed" onClick={clearDone}>Clear completed</button>
	</footer>
}



/******* S.D.G. *******/



