/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const Header = (props) => {
    return <header className="header">
        {props.children}
    </header>
}


/******* S.D.G. *******/



