/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const Main = (props) => {
	return <section className="main">
		{props.children}
	</section>
}



/******* S.D.G. *******/



