/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React, {useState, useEffect} from "react";
import {newTodoChanged, newTodoKeyPressed} from "../../../gen/todo/ActionFunctions";


export const NewTodoInput = (props) => {
	return <input
		value={props.newTodo}
		placeholder="What needs to be done?"
		onKeyUp={(event) => newTodoKeyPressed(event.keyCode)}
		onChange={e => newTodoChanged(e.target.value)}
		className="new-todo"
		id="newTodoInput"
	/>
}



/******* S.D.G. *******/



