/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React, {useState, useEffect} from "react";
import {newTodoChanged, newTodoKeyPressed} from "../../../gen/todo/ActionFunctions";


export const NewTodoInput = (props) => {
	const [newTodo, setNewTodo] = useState(props.newTodo);
	useEffect(() => {
		setNewTodo(props.newTodo)
	}, [props.newTodo]);
	const onChange = (e) => {
		setNewTodo(e.target.value);
		newTodoChanged(e.target.value);
	}
	return <input
		value={newTodo}
		placeholder="What needs to be done?"
		onKeyUp={(event) => newTodoKeyPressed(event.keyCode)}
		onChange={onChange}
		className="new-todo"
		id="newTodoInput"
	/>
}



/******* S.D.G. *******/



