/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";


export const Spinner = (props) => {
	if (props.loading) {
		return <div className="spinner"/>
	}
	return null;
}



/******* S.D.G. *******/



