/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import React from "react";

export function uiElement(attributes) {
	if (attributes.loading) {
		return <div className="spinner"/>
	}
	return null;
}



/******* S.D.G. *******/



