/********************************************************************************
 * generated by de.acegen 1.5.6
 ********************************************************************************/




import React from "react";


export const TestGroup = (props) => {
	if (props.isTest === true) {
		return <Test {...props}/>;
	}
	return null;
}



/******* S.D.G. *******/



