/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React from "react";

import { TodoListItem } from "./todos/TodoListItem";

function filter(todo, filter) {
	return filter === 'all' || filter === 'done' && todo.done === true || filter === 'open' && todo.done === false;
}

export const Todos = (props) => {
	return <div>
		<ul className="todo-list">
			{(props.todoList) ? props.todoList.filter((todo) => filter(todo, props.filter)).map((todoElement) => {
				return <TodoListItem
					{...todoElement}
					editedTodoId={props.editedTodoId}
					editedDescription={props.editedDescription}
					key={todoElement.id}
				/>
			}) : []}
		</ul>
	</div>
}



/******* S.D.G. *******/



