/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {TodoListItem} from "./todos/TodoListItem";

export const Todos = (props) => {
    return <div>
        <ul className="todo-list">
            {props.children}
        </ul>
    </div>
}


/******* S.D.G. *******/



