/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import React from "react";
import {TodoListItemComponent} from "../../../gen/components/container/todos/TodoListItemComponent";

function filter(todo, filter) {
	return filter === 'all' || filter === 'done' && todo.done === true || filter === 'open' && todo.done === false;
}

export function uiElement(attributes) {
	return <div>
		<ul className="todo-list">
			{(attributes.todoList) ? attributes.todoList.filter((todo) => filter(todo, attributes.filter)).map((todoElement) => {
				return <TodoListItemComponent
					{...todoElement}
					editedTodoId={attributes.editedTodoId}
					editedDescription={attributes.editedDescription}
					key={todoElement.id}
				/>
			}) : []}
		</ul>
	</div>
}



/******* S.D.G. *******/



