/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {input, li} from "../../../gen/components/ReactHelper";
import {editedTodoChanged, editedTodoKeyPressed} from "../../../gen/todo/ActionFunctions";

export function jsx(attributes) {
	return li(
		undefined,
		{
			className: 'editing',
			id: attributes.id
		},
		[
			input(
				{
					className: "edit",
					value: attributes.editedTodo ? attributes.editedTodo.editedDescription : "",
					onKeyPress: (event) => editedTodoKeyPressed(event.charCode),
					onChange: (event) => editedTodoChanged(event.target.value),
					id: attributes.id
				}
			)
		]
	);
}



/******* S.D.G. *******/



