/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSetHashAction from "../../../gen/init/actions/AbstractSetHashAction";

export default class SetHashAction extends AbstractSetHashAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



