/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractSetHashCommand from "../../../gen/init/commands/AbstractSetHashCommand";

export default class SetHashCommand extends AbstractSetHashCommand {
    execute(data) {
        console.log("SetHashCommand", data);
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



