/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import React, {useState, useEffect} from "react";
import {
	deleteTodo,
	editedTodoChanged,
	editedTodoKeyPressed,
	editTodo, newTodoChanged,
	toggleTodo
} from "../../../../gen/todo/ActionFunctions";


export const TodoListItem = (props) => {
	if (props.editedTodoId === props.id) {
		return <li className="editing" id={props.id}>
			<input
				className="edit"
				value={props.editedDescription}
				onKeyUp={(event) => editedTodoKeyPressed(event.keyCode)}
				onChange={(event) => editedTodoChanged(event.target.value)}
				id="editedTodo"
			/>
		</li>
	}
	return <li className={props.done ? 'completed' : ''} id={props.id}>
		<div className="view" id={props.id}>
			<input
				id={`checkbox_${props.id}`}
				className="toggle"
				type="checkbox"
				checked={props.done}
				onChange={() => toggleTodo(props.id)}
			/>
			<label
				id={`edit_${props.id}`}
				onDoubleClick={() => editTodo(props.id)}
			>
				{props.description}
			</label>
			<button
				id={`delete_${props.id}`}
				className="destroy"
				onClick={() => deleteTodo(props.id)}
			>×</button>
		</div>
	</li>
}



/******* S.D.G. *******/



