/********************************************************************************
 * generated by de.acegen 1.2.1
 ********************************************************************************/




import React from "react";
import {
	deleteTodo,
	editedTodoChanged,
	editedTodoKeyPressed,
	editTodo,
	toggleTodo
} from "../../../../gen/todo/ActionFunctions";

export function uiElement(attributes) {
	if (attributes.editedTodoId === attributes.id) {
		return <li className="editing" id={attributes.id}>
			<input
				className="edit"
				value={attributes.editedDescription}
				onKeyPress={(event) => editedTodoKeyPressed(event.charCode)}
				onChange={(event) => editedTodoChanged(event.target.value)}
				id="editedTodo"
			/>
		</li>
	}
	return <li className={attributes.done ? 'completed' : ''} id={attributes.id}>
		<div className="view" id={attributes.id}>
			<input
				id={`checkbox_${attributes.id}`}
				className="toggle"
				type="checkbox"
				checked={attributes.done}
				onChange={() => toggleTodo(attributes.id)}
			/>
			<label
				id={`edit_${attributes.id}`}
				onDoubleClick={() => editTodo(attributes.id)}
			>
				{attributes.description}
			</label>
			<button
				id={`delete_${attributes.id}`}
				className="destroy"
				onClick={() => deleteTodo(attributes.id)}
			>×</button>
		</div>
	</li>
}



/******* S.D.G. *******/



