/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




module.exports = {
	twoTodosAreDisplayed: async function(driver, testId) {
		fail("twoTodosAreDisplayed not implemented");
	},
	twoTodosAreDisplayed: async function(driver, testId) {
		fail("twoTodosAreDisplayed not implemented");
	}
}



/******* S.D.G. *******/


