/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/

import * as ActionIds from "../gen/todo/TodoActionIds"

export function getCypressFor(action, args) {
    if (ActionIds.init === action) {
        return cy.visit(`http://127.0.0.1:9999/${args[0]}`)
    }
}

export function wait(timeInMillis) {
    return cy.wait(timeInMillis)
}

export function testId() {
    let d = new Date().getTime();
    return 'xxxxxxxx'.replace(/[xy]/g, function (c) {
        let r = (d + Math.random() * 16) % 16 | 0;
        d = Math.floor(d / 16);
        return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    });

}



/******* S.D.G. *******/




