/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div } from "../../gen/components/ReactHelper";

export function jsx(attributes) {
	return div("container", {}, []);
}



/******* S.D.G. *******/



