/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {pre} from "../../gen/components/ReactHelper";

export function jsx(attributes) {
    if (attributes.errorMessage) {
        return pre(attributes.errorMessage, {className: "error"});
    }
    return "";
}

/******* S.D.G. *******/



