/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/


import {pre} from "../../gen/components/ReactHelper";

export function uiElement(attributes) {
    if (attributes.errorMessage) {
        return pre({class: "error"}, [attributes.errorMessage]);
    }
    return "";
}

/******* S.D.G. *******/



