/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { generic, span, ul } from "../../gen/components/ReactHelper";

export function uiElement(attributes) {
	const itemsString = attributes.itemCount === 1 ? 'item' : 'items';
	return generic("footer", {class: "footer"},
		[
			span({class: "todo-count"},
				[
					`${attributes.itemCount} ${itemsString} left`,
					ul({class:"filters"},
						[

						]
					)
				]
			)
		]
	);
}



/******* S.D.G. *******/



