/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import {div, generic} from "../../gen/components/ReactHelper";
import React from "react";

export function uiElement(attributes) {
	if (attributes.loading) {
		return div({class: "spinner"});
	}
	return ""
}


/******* S.D.G. *******/



