/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import { div } from "../../gen/components/ReactHelper";
import React from "react";

export function jsx(attributes) {
	if (attributes.loading) {
		return div(undefined, {className: "spinner"});
	}
	return ""
}


/******* S.D.G. *******/



