/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import {div, todoListItem, ul} from "../../gen/components/ReactHelper";

function filter(todo, filter) {
	return filter === 'all' || filter === 'done' && todo.done === true || filter === 'open' && todo.done === false;
}

export function jsx(attributes) {
	return div(
		undefined,
		undefined,
		[
			ul(
				{
					className: "todo-list"
				},
				[
					(attributes.todos && attributes.todos.todoList) ? attributes.todos.todoList.filter((todo) => filter(todo, attributes.filter)).map((todoElement) => {
						return todoListItem(
							{
								...todoElement,
								editedTodo: attributes.todos.editedTodo
							}
						)
					}) : []
				]
			)
		]
	)
}



/******* S.D.G. *******/



