/********************************************************************************
 * generated by de.acegen 1.1.0
 ********************************************************************************/




import {div, todoListItem, ul} from "../../gen/components/ReactHelper";

function filter(todo, filter) {
	return filter === 'all' || filter === 'done' && todo.done === true || filter === 'open' && todo.done === false;
}

export function uiElement(attributes) {
	console.log("uiElement", attributes);
	return div(
		{},
		[
			ul(
				{
					class: "todo-list"
				},
				[
					(attributes.todoList) ? attributes.todoList.filter((todo) => filter(todo, attributes.filter)).map((todoElement) => {
						return todoListItem(
							{
								...todoElement,
								editedTodoId: attributes.editedTodoId,
								editedDescription: attributes.editedDescription,
							}
						)
					}) : []
				]
			)
		]
	)
}



/******* S.D.G. *******/



