/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {clearDone} from "../../../../gen/todo/ActionFunctions";

export const ClearDone = (props) => {
    return <button
        className="clear-completed"
        onClick={clearDone}
    >
        Clear completed
    </button>
}


/******* S.D.G. *******/



