/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const ClearDone = (props) => {
    return <button
        className="clear-completed"
        onClick={props.onClick}
    >
        Clear completed
    </button>
}


/******* S.D.G. *******/



