/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const Filter = (props) => {
    return <ul className="filters">
        <li>
            <a onClick={() => props.onChange("all")} className={props.value === 'all' ? 'selected' : ''}>All</a>
        </li>
        <li>
            <a onClick={() => props.onChange("open")} className={props.value === 'open' ? 'selected' : ''}>Active</a>
        </li>
        <li>
            <a onClick={() => props.onChange("done")} className={props.value === 'done' ? 'selected' : ''}>Completed</a>
        </li>
    </ul>

}


/******* S.D.G. *******/



