/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCalculateItemCountAction from "../../../gen/todo/actions/AbstractCalculateItemCountAction";

export default class CalculateItemCountAction extends AbstractCalculateItemCountAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



