/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCalculateItemCountAction from "../../../gen/todo/actions/AbstractCalculateItemCountAction";

export default class CalculateItemCountAction extends AbstractCalculateItemCountAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



