/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractChangeFilterAction from "../../../gen/todo/actions/AbstractChangeFilterAction";

export default class ChangeFilterAction extends AbstractChangeFilterAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



