/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractClearDoneAction from "../../../gen/todo/actions/AbstractClearDoneAction";

export default class ClearDoneAction extends AbstractClearDoneAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



