/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateCategoryAction from "../../../gen/todo/actions/AbstractCreateCategoryAction";

export default class CreateCategoryAction extends AbstractCreateCategoryAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



