/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateTodoAction from "../../../gen/todo/actions/AbstractCreateTodoAction";

export default class CreateTodoAction extends AbstractCreateTodoAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



