/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractDeleteTodoAction from "../../../gen/todo/actions/AbstractDeleteTodoAction";

export default class DeleteTodoAction extends AbstractDeleteTodoAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



