/********************************************************************************
 * generated by de.acegen 0.9.12
 ********************************************************************************/




import AbstractDisplayErrorAction from "../../../gen/todo/actions/AbstractDisplayErrorAction";

export default class DisplayErrorAction extends AbstractDisplayErrorAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



