/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditTodoAction from "../../../gen/todo/actions/AbstractEditTodoAction";

export default class EditTodoAction extends AbstractEditTodoAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



