/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractEditedTodoKeyPressedAction from "../../../gen/todo/actions/AbstractEditedTodoKeyPressedAction";

export default class EditedTodoKeyPressedAction extends AbstractEditedTodoKeyPressedAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



