/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditedTodoKeyPressedAction from "../../../gen/todo/actions/AbstractEditedTodoKeyPressedAction";

export default class EditedTodoKeyPressedAction extends AbstractEditedTodoKeyPressedAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



