/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditedTodoChangedAction from "../../../gen/todo/actions/AbstractEditedTodoChangedAction";

export default class EditedTodoChangedAction extends AbstractEditedTodoChangedAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



