/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetTodoListAction from "../../../gen/todo/actions/AbstractGetTodoListAction";

export default class GetTodoListAction extends AbstractGetTodoListAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



