/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractGetTodoListWithoutCategoryCheckAction from "../../../gen/todo/actions/AbstractGetTodoListWithoutCategoryCheckAction";

export default class GetTodoListWithoutCategoryCheckAction extends AbstractGetTodoListWithoutCategoryCheckAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



