/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetTodoListWithoutCategoryCheckAction from "../../../gen/todo/actions/AbstractGetTodoListWithoutCategoryCheckAction";

export default class GetTodoListWithoutCategoryCheckAction extends AbstractGetTodoListWithoutCategoryCheckAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



