/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractInitAction from "../../../gen/todo/actions/AbstractInitAction";

export default class InitAction extends AbstractInitAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



