/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractNewTodoChangedAction from "../../../gen/todo/actions/AbstractNewTodoChangedAction";

export default class NewTodoChangedAction extends AbstractNewTodoChangedAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



