/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractNewTodoKeyPressedAction from "../../../gen/todo/actions/AbstractNewTodoKeyPressedAction";

export default class NewTodoKeyPressedAction extends AbstractNewTodoKeyPressedAction {

    initActionData() {
    }

}




/******* S.D.G. *******/



