/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractNewTodoKeyPressedAction from "../../../gen/todo/actions/AbstractNewTodoKeyPressedAction";

export default class NewTodoKeyPressedAction extends AbstractNewTodoKeyPressedAction {

    initActionData() {
    	//add not replayable data to action data in order to freeze for replay (e.g. time or date)
    }

}




/******* S.D.G. *******/



