/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleTodoAction from "../../../gen/todo/actions/AbstractToggleTodoAction";

export default class ToggleTodoAction extends AbstractToggleTodoAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



