/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractToggleAllAction from "../../../gen/todo/actions/AbstractToggleAllAction";

export default class ToggleAllAction extends AbstractToggleAllAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



