/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateTodoAction from "../../../gen/todo/actions/AbstractUpdateTodoAction";

export default class UpdateTodoAction extends AbstractUpdateTodoAction {

    initActionData(data) {
    	return data;
    }

}




/******* S.D.G. *******/



