/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import AbstractChangeFilterCommand from "../../../gen/todo/commands/AbstractChangeFilterCommand";

export default class ChangeFilterCommand extends AbstractChangeFilterCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



