/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractCreateTodoCommand from "../../../gen/todo/commands/AbstractCreateTodoCommand";

export default class CreateTodoCommand extends AbstractCreateTodoCommand {

    validateCommandData(data) {
        if (data.description) {
            return true;
        } else {
            this.addEmptyOutcome(data);
            return false;
        }
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        data.newTodo = "";
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }

}




/******* S.D.G. *******/



