/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractCreateCategoryCommand from "../../../gen/todo/commands/AbstractCreateCategoryCommand";

export default class CreateCategoryCommand extends AbstractCreateCategoryCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(resolve) {
        this.addOkOutcome();
    	resolve();
    }
    handleError(resolve, reject) {
    	reject(this.commandData.error);
    }
}




/******* S.D.G. *******/



