/********************************************************************************
 * generated by de.acegen 1.0.5
 ********************************************************************************/




import AbstractDisplayErrorCommand from "../../../gen/todo/commands/AbstractDisplayErrorCommand";

export default class DisplayErrorCommand extends AbstractDisplayErrorCommand {
    execute() {
    	this.addOkOutcome();
    }
}




/******* S.D.G. *******/



