/********************************************************************************
 * generated by de.acegen 0.9.12
 ********************************************************************************/




import AbstractDisplayErrorCommand from "../../../gen/todo/commands/AbstractDisplayErrorCommand";

export default class DisplayErrorCommand extends AbstractDisplayErrorCommand {
    execute() {
    	this.commandData.outcome = this.ok;
    }
}




/******* S.D.G. *******/



