/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditedTodoKeyPressedCommand from "../../../gen/todo/commands/AbstractEditedTodoKeyPressedCommand";

export default class EditedTodoKeyPressedCommand extends AbstractEditedTodoKeyPressedCommand {
    execute(data) {
        if (data.charCode === 13) {
            this.addEnterOutcome(data);
        } else {
            this.addNotEnterOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/



