/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditTodoCommand from "../../../gen/todo/commands/AbstractEditTodoCommand";

export default class EditTodoCommand extends AbstractEditTodoCommand {
    execute(data) {
        const todo = data.todoList.find(todo => todo.id === data.id);
        todo.readOnly = false
        this.addOkOutcome(data);
        return data;
    }
}




/******* S.D.G. *******/



