/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractEditedTodoKeyPressedCommand from "../../../gen/todo/commands/AbstractEditedTodoKeyPressedCommand";

export default class EditedTodoKeyPressedCommand extends AbstractEditedTodoKeyPressedCommand {
    execute() {
        if (this.commandData.charCode === 13) {
            this.addEnterOutcome();
        } else {
            this.addNotEnterOutcome();
        }
    }
}




/******* S.D.G. *******/



