/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditTodoCommand from "../../../gen/todo/commands/AbstractEditTodoCommand";

export default class EditTodoCommand extends AbstractEditTodoCommand {
    execute(data) {
        const todo = data.todoList.filter(todo => todo.id === data.id);
        data.editedTodoId = todo[0].id;
        data.editedDescription = todo[0].description;
        this.addOkOutcome(data);
        return data;
    }
}




/******* S.D.G. *******/



