/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditedTodoChangedCommand from "../../../gen/todo/commands/AbstractEditedTodoChangedCommand";

export default class EditedTodoChangedCommand extends AbstractEditedTodoChangedCommand {
    execute(data) {
        const todo = data.todoList.find(todo => todo.id === data.id);
        todo.descriptionInput.editedDescription = data.value
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



