/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractEditedTodoKeyPressedCommand from "../../../gen/todo/commands/AbstractEditedTodoKeyPressedCommand";

export default class EditedTodoKeyPressedCommand extends AbstractEditedTodoKeyPressedCommand {
    execute(data) {
        if (data.keyCode === 13) {
            this.addEnterOutcome(data);
        } else if (data.keyCode === 27) {
            this.addEscOutcome(data);
            data.editedTodoId = null;
            data.editedDescription = "";
        } else {
            this.addNotEnterOutcome(data);
        }
    	return data;
    }
}




/******* S.D.G. *******/



