/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractGetTodoListCommand from "../../../gen/todo/commands/AbstractGetTodoListCommand";

export default class GetTodoListCommand extends AbstractGetTodoListCommand {

    validateCommandData() {
    	return true;
    }

    handleResponse(data, resolve) {
        if (!data.todoList) {
            this.addCategoryDoesNotExistOutcome(data)
        } else {
            this.addOkOutcome(data);
        }
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }
}




/******* S.D.G. *******/



