/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/


import AbstractInitCommand from "../../../gen/todo/commands/AbstractInitCommand";

export default class InitCommand extends AbstractInitCommand {
    execute(data) {
        data.newTodo = {
            value: ""
        };
        data.checked = false;
        this.addOkOutcome(data);
        return data;
    }
}


/******* S.D.G. *******/



