/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractNewTodoChangedCommand from "../../../gen/todo/commands/AbstractNewTodoChangedCommand";

export default class NewTodoChangedCommand extends AbstractNewTodoChangedCommand {
    execute(data) {
    	this.addOkOutcome(data);
    	return data;
    }
}




/******* S.D.G. *******/



