/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractNewTodoKeyPressedCommand from "../../../gen/todo/commands/AbstractNewTodoKeyPressedCommand";

export default class NewTodoKeyPressedCommand extends AbstractNewTodoKeyPressedCommand {
    execute() {
        if (this.commandData.charCode === 13) {
            this.addEnterOutcome();
        } else {
            this.addNotEnterOutcome();
        }
    }
}




/******* S.D.G. *******/



