/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/




import AbstractNewTodoKeyPressedCommand from "../../../gen/todo/commands/AbstractNewTodoKeyPressedCommand";

export default class NewTodoKeyPressedCommand extends AbstractNewTodoKeyPressedCommand {
    execute(data) {
        if (data.charCode === 13) {
            this.addEnterOutcome(data);
        } else {
            this.addNotEnterOutcome(data);
        }
        return data;
    }
}




/******* S.D.G. *******/



