/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateTodoCommand from "../../../gen/todo/commands/AbstractUpdateTodoCommand";

export default class UpdateTodoCommand extends AbstractUpdateTodoCommand {

    validateCommandData(data) {
        const todo = data.todoList.find(todo => todo.id === data.id);
        if (todo.descriptionInput.editedDescription) {
            data.description = todo.descriptionInput.editedDescription
            return true;
        } else {
            this.addEmptyOutcome(data);
            return false;
        }
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }

}




/******* S.D.G. *******/



