/********************************************************************************
 * generated by de.acegen 1.3.0
 ********************************************************************************/




import AbstractUpdateTodoCommand from "../../../gen/todo/commands/AbstractUpdateTodoCommand";

export default class UpdateTodoCommand extends AbstractUpdateTodoCommand {

    validateCommandData(data) {
        if (data.description) {
            return true;
        } else {
            this.addEmptyOutcome(data);
            data.editedTodoId = null;
            data.editedDescription = "";
            return false;
        }
    }

    handleResponse(data, resolve) {
        this.addOkOutcome(data);
        data.editedTodoId = null;
        data.editedDescription = "";
    	resolve(data);
    }
    handleError(data, resolve, reject) {
    	reject(data.error);
    }

}




/******* S.D.G. *******/



