/********************************************************************************
 * generated by de.acegen 1.0.2
 ********************************************************************************/

import * as ScenarioUtils from "../src/ScenarioUtils";
import * as ActionIds from "../gen/todo/ActionIds";

context('InitAllWithCreateCategory', () => {
    beforeEach(() => {
    })

    it('should change appState', () => {
        ScenarioUtils.getCypressFor(ActionIds.init, ["#/category1"]).should(() => {
            cy.wait(500).should(() => {
                const appState = JSON.parse(localStorage.getItem('appState'));
                expect(appState.filter, 'should be all').to.eq("all")
            })
        })
    })
})

