/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const DeleteTodo = (props) => {
	return <button
		id={`delete_${props.id}`}
		className="destroy"
		onClick={() => props.onClick(props.id)}
	>×</button>
}



/******* S.D.G. *******/



