/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

export const DescriptionInput = (props) => {
    if (props.readOnly) {
        return <label
            id={`edit_${props.id}`}
            onDoubleClick={() => props.onDoubleClick(props.id)}
        >
            {props.description}
        </label>
    }
    return <input
        className="edit"
        id={`editedTodo_${props.id}`}
        value={props.editedDescription}
        onChange={(event) => props.onChange(event.target.value, props.id)}
        onKeyUp={(event) => props.onKeyUp(event.keyCode, props.id)}
    />
}


/******* S.D.G. *******/



