/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/


import React from "react";

import {editedTodoChanged, editTodo} from "../../../../../gen/todo/ActionFunctions";
import {editedTodoKeyPressed} from "../../../../../gen/todo/ActionFunctions";

export const DescriptionInput = (props) => {
    if (props.readOnly) {
        return <label
            id={`edit_${props.id}`}
            onDoubleClick={() => editTodo(props.id)}
        >
            {props.description}
        </label>
    }
    return <input
        className="edit"
        value={props.editedDescription}
        onChange={(event) => editedTodoChanged(event.target.value, props.id)}
        onKeyUp={(event) => editedTodoKeyPressed(event.keyCode, props.id)}
    />
}


/******* S.D.G. *******/



