/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/
import {setContainerState} from "../gen/components/ContainerContainer";
import * as R from "ramda";


export let appState = {};

export function get(path) {
    const lens = R.lensPath(path);
    return R.view(lens, appState);
}

export function getLocation(path) {
    const locationHash = location.hash
    if (R.last(path) === "value") {
        const last = R.last(locationHash.split('/'))
        if (R.includes(last, ["all", "open", "done", '#'])) {
            return last
        }
        return "all"
    }
    if (R.last(path) === "categoryId") {
        const hashParts = locationHash.split('/')
        if (!hashParts || hashParts.length <= 1) {
            return "defaultCategory"
        }
        const first = hashParts[1];
        if (R.includes(first, ["all", "open", "done", ""])) {
            return "defaultCategory"
        }
        return first
    }
}

export function getStorage(path) {
    return localStorage.getItem(R.last(path));
}

function normalizeData(data, path, attributes) {
    const value = data[R.last(path)];
    if (!value) {
        return value;
    }
    if (attributes) {
        return R.pick(attributes, data[R.last(path)]);
    } else {
        return data[R.last(path)]
    }
}

export function set(data, path, attributes) {
    const normalizedData = normalizeData(data, path, attributes);
    const lens = R.lensPath(path);
    appState = R.set(lens, normalizedData, appState);
}

export function setLocation(data, path) {
    const locationHash = location.hash
    if (R.last(path) === "value") {
        const hashParts = locationHash.split('/')
        const last = R.last(hashParts)
        if (R.includes(last, ["all", "open", "done", '#'])) {
            hashParts.pop()
        }
        hashParts.push(data[R.last(path)])
        location.hash = hashParts.join('/')
    }
}

export function setStorage(data, path) {
    const lastParam = R.last(path);
    if (data[lastParam]) {
        localStorage.setItem(lastParam, data[lastParam]);
    } else {
        localStorage.removeItem(lastParam);
    }
}

export function merge(data, path, attributes) {
    if (attributes) {
        const lens = R.lensPath(path);
        const appStateValue = R.view(lens, appState);
        const normalizedData = normalizeData(data, path, attributes);
        const mergedData = R.mergeDeepRight(appStateValue, normalizedData);
        appState = R.set(lens, mergedData, appState);
    } else {
        set(data, path, attributes);
    }
}

export function mergeLocation(data, path) {
    if (data[R.last(path)]) {
        location.hash = data[R.last(path)];
    }
}

export function mergeStorage(data, path) {
    const lastParam = R.last(path);
    if (data[lastParam]) {
        localStorage.setItem(lastParam, data[lastParam]);
    }
}

export function createInitialAppState() {
    appState = {};
}

export function setInitialAppState(initialAppState) {
    appState = initialAppState;
}


export function stateUpdated() {
    setContainerState(appState.container);
}


/******* S.D.G. *******/



