/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";


export const Heading = (props) => {
	return <h1>
		<span>todos</span>
		{props.children}
	</h1>
}



/******* S.D.G. *******/



