/********************************************************************************
 * generated by de.acegen
 ********************************************************************************/




import React from "react";

export const NewTodo = (props) => {
	return <input
		value={props.value}
		placeholder="What needs to be done?"
		className="new-todo"
		id="newTodoInput"
		onChange={(event) => props.onChange(event.target.value)}
		onKeyUp={(event) => props.onKeyUp(event.keyCode)}
	/>
}



/******* S.D.G. *******/



